*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 01:48:14 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 31 October 2017 23:03:19
os: Linux-2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014
nodename: iZ94zgbucl2Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/django/S-G_Consulting/testdb/testdb/Ylk
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/django/S-G_Consulting/testdb/testdb/Ylk/Ylk
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.6.2 (default, Oct 10 2017, 23:05:47)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xbda1a0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291072 bytes (284 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'Ylk'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 30870, cores: 1)
spawned uWSGI worker 2 (pid: 30872, cores: 1)
spawned uWSGI worker 3 (pid: 30873, cores: 1)
spawned uWSGI worker 4 (pid: 30874, cores: 1)
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 01:49:43 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 31 October 2017 23:03:19
os: Linux-2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014
nodename: iZ94zgbucl2Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/django/S-G_Consulting/testdb/testdb/Ylk
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/django/S-G_Consulting/testdb/testdb/Ylk
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8001).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.15 (64bit) on [Thu Nov  9 01:50:44 2017] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-18) on 31 October 2017 23:03:19
os: Linux-2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014
nodename: iZ94zgbucl2Z
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/django/S-G_Consulting/testdb/testdb/Ylk
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/django/S-G_Consulting/testdb/testdb/Ylk
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:8001).
bind(): Address already in use [core/socket.c line 769]
